apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestion-commandes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gestion-commandes
  template:
    metadata:
      labels:
        app: gestion-commandes
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '5100'
        prometheus.io/path: '/metrics'
    spec:
      initContainers:
      - name: wait-for-mongodb
        image: busybox:1.28
        command: ['sh', '-c', "until nc -z -v -w30 mongodb 27017; do echo waiting for mongodb; sleep 5; done"]
      containers:
      - name: gestion-commandes
        image: achrefs161/order-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5100
        env:
        - name: PORT
          value: "5100"
        - name: MON_URI
          value: "mongodb://mongodb:27017/gestion-commandes"
        - name: AUTH_SERVICE_DB_URI
          value: "mongodb://mongodb:27017/authentication-service"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: shop-secrets
              key: JWT_SECRET
