apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-catalogue
  template:
    metadata:
      labels:
        app: product-catalogue
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '4000'
        prometheus.io/path: '/metrics'
    spec:
      initContainers:
      - name: wait-for-postgres
        image: busybox:1.28
        command: ['sh', '-c', "until nc -z -v -w30 postgres 5432; do echo waiting for postgres; sleep 5; done"]
      containers:
      - name: product-catalogue
        image: achrefs161/product-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
        env:
        - name: PORT
          value: "4000"
        - name: DATABASE_URL
          value: "postgres://user:password@postgres:5432/product_db"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: shop-secrets
              key: JWT_SECRET
        - name: BASE_URL
          value: "http://shop.local/products" 
        volumeMounts:
        - name: uploads-storage
          mountPath: /app/uploads
      volumes:
      - name: uploads-storage
        persistentVolumeClaim:
          claimName: uploads-pvc
