apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-authentication
  template:
    metadata:
      labels:
        app: user-authentication
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '5000'
        prometheus.io/path: '/metrics'
    spec:
      initContainers:
      - name: wait-for-mongodb
        image: busybox:1.28
        command: ['sh', '-c', "until nc -z -v -w30 mongodb 27017; do echo waiting for mongodb; sleep 5; done"]
      containers:
      - name: user-authentication
        image: achrefs161/user-auth-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        - name: MONGO_URI
          value: "mongodb://mongodb:27017/authentication-service"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: shop-secrets
              key: JWT_SECRET
