apiVersion: v1
kind: Secret
metadata:
  name: shop-secrets
type: Opaque
data:
  # Values are base64 encoded
  # JWT_SECRET: supersecretkey
  JWT_SECRET: c3VwZXJzZWNyZXRrZXk=
  # POSTGRES_PASSWORD: password
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  # POSTGRES_USER: user
  POSTGRES_USER: dXNlcg==
  # POSTGRES_DB: product_db
  POSTGRES_DB: cHJvZHVjdF9kYg==
